import numpy as np
arr = np.random.randint(1, 100, size = (10,5)) # sample (row) - 10, feature (colum) - 4


In [3]:
b = arr.reshape(5,10)
b.shape
b

array([[63, 25,  5,  4, 36,  1, 98, 31,  7, 77],
       [23, 85,  9, 33, 12, 39, 55, 42, 50, 79],
       [87, 24, 78, 28, 29, 47, 94, 48, 43, 90],
       [11, 57, 64, 68, 74,  5, 80, 12,  8, 13],
       [89, 87, 28, 86, 95, 18, 66, 30, 29, 80]], dtype=int32)

In [4]:
# converting to 1D array using flatten() ---(row wise combine)
flatten = b.flatten()
print(flatten.ndim)
print(flatten) # row wise combine


1
[63 25  5  4 36  1 98 31  7 77 23 85  9 33 12 39 55 42 50 79 87 24 78 28
 29 47 94 48 43 90 11 57 64 68 74  5 80 12  8 13 89 87 28 86 95 18 66 30
 29 80]


In [5]:
# column wise combining using ravel(arr,order='C/F') -------(c-> is use for row , and f-> is use for column wise)
column_wise_flattening = np.ravel(b, order = 'F')

print(column_wise_flattening)


[63 23 87 11 89 25 85 24 57 87  5  9 78 64 28  4 33 28 68 86 36 12 29 74
 95  1 39 47  5 18 98 55 94 80 66 31 42 48 12 30  7 50 43  8 29 77 79 90
 13 80]


In [6]:
# dui ta set ke aksathe kora using 
a = np.random.randint(1, 10, size = (2,3))
b = np.random.randint(20, 30, size = (2,3))
print(a)
print(b)

[[4 5 2]
 [4 7 9]]
[[27 25 24]
 [24 21 28]]


### concatenate

In [7]:
# je shape a amra concatanet kortace sai shape ta jeno same thake 
con_row = np.concatenate((a,b), axis = 0) # row wise (colum same )
print(con_row)

con_col = np.concatenate((a,b), axis = 1) #column wise (row same )
print(con_col)

[[ 4  5  2]
 [ 4  7  9]
 [27 25 24]
 [24 21 28]]
[[ 4  5  2 27 25 24]
 [ 4  7  9 24 21 28]]


In [8]:
# error 

# row wise concatenate korar shomoi column same thakebe
# col wise concat korar shomoi row ta same thakte hobe 

x = np.random.randint(1, 10 , size = (2,3)) 
y = np.random.randint(1, 10, size = (1, 3))

r = np.concatenate((x,y), axis = 0) 
# r = np.concatenate((x,y), axis = 1)   #karon row same nai tai col wise hone na 
print(r)

[[1 2 9]
 [4 7 2]
 [3 1 7]]


In [9]:
mat = np.array([[10,20,30],
               [30,40,50]
                ])
transpose = mat.T # row wise hoi transpose
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [10]:
#array split
a = np.random.randint(1,10, size =(10,))

print(a)
print(len(a))
# array split aikhane korno error daina equaly na korte parle aktake samne nea asa
splitted_array = np.array_split(a,3)
print(splitted_array)


#split --> normal array split.
# splitted_array = np.split(a,3)


[1 9 7 3 3 8 5 2 2 8]
10
[array([1, 9, 7, 3], dtype=int32), array([3, 8, 5], dtype=int32), array([2, 2, 8], dtype=int32)]


## arithmetic operator and mathematical functions

In [11]:
# mathematiecal operator
#faster for vectorization
# amra jode chai je koon row wise kore add and multiple tahole ababe korte hone
# ne korno aktai np.array() use kore oi hobe

x = ([10, 8, 30, 100])
y = np.array([2,3,4,5])

print(x)

# add = x+y
add = np.add(x,y)
print(add)


# Subtraction
sub = np.subtract(x, y)
# sub = x-y
print(sub)


# Multiplication
mul = np.multiply(x, y)
# mul = x*y
print(mul)


# Division
div = np.divide(x, y)
# div = x/y
print(div)


# Remainder (modulus)
rem = np.remainder(x, y)
# remainder = x % y
# print(remainder)


#10+2 20+3 30+4 40+5  amon kore kaj kore


[10, 8, 30, 100]
[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]


In [12]:
# mathametical function

# trigonometry

# sin, cos , tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)


tan_val = np.tan(x)
print(tan_val)

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 0.64836083 -6.79971146 -6.4053312  -0.58721392]


In [13]:
# degree to radiant =-->  rad2deg()
deg_con = np.rad2deg(x)
print(deg_con)

# raiant to degree -->. deg2rad
rad_con = np.deg2rad(x)
print(rad_con)

[ 572.95779513  458.3662361  1718.87338539 5729.57795131]
[0.17453293 0.13962634 0.52359878 1.74532925]


In [14]:
# log ---> ar mane hoi lo kono akta number ke koi bar bag kora jai
print(x)

base_10_long_val = np.log10(x)# 10 dea bag koi ber jai
print(base_10_long_val)


two_diye_bhag = np.log2(x) # 2 dea bag koi bar jai
print(two_diye_bhag)

[10, 8, 30, 100]
[1.         0.90308999 1.47712125 2.        ]
[3.32192809 3.         4.9068906  6.64385619]


In [15]:
# squir root mane hoce borgo mul bar kora sqrt
sqrt = np.sqrt(x)
print(sqrt)

[ 3.16227766  2.82842712  5.47722558 10.        ]


In [16]:
#different
x = np.array([10, 8, 30, 100])

s = np.sum(x)
print(s)

#prefix sum
cumul = np.cumsum(x)

print(cumul)

148
[ 10  18  48 148]


In [17]:
x = np.array([10, 8, 16, 100])

result = x + 2
# print(result)



matrix = np.array([[10, 20, 30],
                [30, 40, 50]
                ])

#akta row ar data ke bola hoi vector
# rules= columns er size and vector er size same hote hobe
# vector = np.array([1,2,3])
vector = np.array([[1,2,3],
                  [2,3,4]])

result = matrix + vector
print(result)

[[11 22 33]
 [32 43 54]]


In [18]:
# comparsion :   >,<,>=,<=, ==,!=

x = np.array([10, 8, 16, 100])
y = np.array([2, 3, 4, 5 ])

greater_than = x>y

print(greater_than)

equal = x==y
print(equal)

# all() --> shob true kina
# any() --> jekono ekta true ase kina 

print(np.all(greater_than))
print(np.any(equal))

[ True  True  True  True]
[False False False False]
True
False


In [19]:
#inplace
x = np.array([10, 8, 16, 100])

z = x.copy()

print(z)

z.sort()

print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [20]:
# copy sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [21]:
# 2d array sorting
mat = np.array([[10,3,5],
                [8,4,9]])

# horizon axis = 1 
hor_sort = np.sort(mat,axis=1)
print(hor_sort)

# vertical axis = 0




[[ 3  5 10]
 [ 4  8  9]]


### Searching

In [22]:
x = np.array([10, 8, 16, 100])
print(x.ndim)
print(x)

1
[ 10   8  16 100]


In [23]:
# np.where(condition , x, y) # if true x, otherwise replace with y 

index = np.where(x==8) # returns index
print(index)

index = np.where(x>8,x,0) # returns array  (jode 8 ar thake boro hoi tahole value ta x oi rakho other
                        # wise tumi atake change kore 0 kore deao
print(index)


(array([1]),)
[ 10   0  16 100]


In [24]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [26]:
index = np.where(mat>8)   # problem 
print(index)

arr = np.where(mat>8, mat,0)
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [32]:
#maximum and minumum value
print(x)
maximu_value_index = np.argmax(x) #index
print("The maximum value:",maximu_value_index,"index") #jode same value thake se first index ke bolbe 

minimum_value_index = np.argmin(x) 
print("The minemum value:",minimum_value_index,"index") 

[ 10   8  16 100]
The maximum value: 3 index
The minemum value: 1 index


## counting in ndarray

In [39]:
a = np.random.randint(1, 100, size = (100,))
print(a)

[56 32 12 72 12  9 52 41 73 84  1  5 29 88 74 84 12 87 31 58 29 37 87 79
 49 69 31 37 42 91 83 40 93  9  9 18 32 74 21 80 68 33 40 12  9 67 46 72
 95  9 56 86 41 30 63 96  5 45 51 37 18 51 93 85 98 57  4 69 53 23 21 21
 67 28 17 19 81  1 39 61 96 34 68 18 59 65 35 77 89 16 92 33 15 16 90 58
 60  3  2 22]


In [43]:
# count_nonzero(a[, axis, keepdims]) -->Counts the number of non-zero values in the array a.
Counting = np.count_nonzero(a<28)
print(Counting)




29


In [44]:
# unique values  ki ke 
unique_value = np.unique(a)
print(unique_value)



[ 1  2  3  4  5  9 12 15 16 17 18 19 21 22 23 28 29 30 31 32 33 34 35 37
 39 40 41 42 45 46 49 51 52 53 56 57 58 59 60 61 63 65 67 68 69 72 73 74
 77 79 80 81 83 84 85 86 87 88 89 90 91 92 93 95 96 98]


In [48]:
unique_value = np.unique(a, return_counts=True) #true rakle uniqe ke koiber asa 

print(unique_value)

(array([ 1,  2,  3,  4,  5,  9, 12, 15, 16, 17, 18, 19, 21, 22, 23, 28, 29,
       30, 31, 32, 33, 34, 35, 37, 39, 40, 41, 42, 45, 46, 49, 51, 52, 53,
       56, 57, 58, 59, 60, 61, 63, 65, 67, 68, 69, 72, 73, 74, 77, 79, 80,
       81, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 95, 96, 98],
      dtype=int32), array([2, 1, 1, 1, 2, 5, 4, 1, 2, 1, 3, 1, 3, 1, 1, 1, 2, 1, 2, 2, 2, 1,
       1, 3, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1]))


In [46]:
unique_value,count = np.unique(a, return_counts=True) # unpacking

print(unique_value)
print(count)

[ 1  2  3  4  5  9 12 15 16 17 18 19 21 22 23 28 29 30 31 32 33 34 35 37
 39 40 41 42 45 46 49 51 52 53 56 57 58 59 60 61 63 65 67 68 69 72 73 74
 77 79 80 81 83 84 85 86 87 88 89 90 91 92 93 95 96 98]
[2 1 1 1 2 5 4 1 2 1 3 1 3 1 1 1 2 1 2 2 2 1 1 3 1 2 2 1 1 1 1 2 1 1 2 1 2
 1 1 1 1 1 2 2 2 2 1 2 1 1 1 1 1 2 1 1 2 1 1 1 1 1 2 1 2 1]


### Statistical Methods

In [50]:
#data loading np.genfromtxt() --> atar madome csv file and text file a kaj korte parben 
data = np.genfromtxt('student_scores.csv' , delimiter = ',',skip_header = 1)
print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [64]:
#statistics
math_marks = data[::, 0:1]  #slicing
print(math_marks.T)

#max
max_math_marks = np.max(math_marks)
print(max_math_marks)

#min
min_math_marks = np.min(math_marks)
print(min_math_marks)

#average np.mean()  --> gor number 
average_math_marks = np.mean(math_marks)
print(average_math_marks)

# np.median()  moddok man
median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [65]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correltaion Matrix:\m", correlation)

Correltaion Matrix:\m [[1.         0.99859154]
 [0.99859154 1.        ]]


 ## linear algebra

In [67]:
A = np.array([[1,2,3],
              [4,5,6]])

B= np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er rwo same length hote hobe 
dot_product = np.dot(A,B)

print(dot_product)

[[ 58  64]
 [139 154]]


In [72]:
# trace --> digonal matrix
t= np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print(t.ndim)

#trace
print(np.trace(t))

2
15


In [74]:
#determinant  matrix
sq_mat = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print(sq_mat.shape)

det_of_sq = np.linalg.det(sq_mat)
print(det_of_sq)

(3, 3)
6.66133814775094e-16


In [76]:
# numpy linalg matrix
rank_sq = np.linalg.matrix_rank(sq_mat)

print(rank_sq)



2


# Quiz problem

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b.shape)

(2, 3)


In [5]:
sin= np.sin(np.pi/2)
print(sin)

1.0


In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


In [8]:
a = np.array([3, 1, 2])
print(np.sort(a))

[1 2 3]


In [10]:
A = np.array([[1,2],[3,4]]) 
B = np.array([[5, 6],[7,8]])
dot = np.dot(A,B)
print(dot)

[[19 22]
 [43 50]]
